/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkoutHistoryRouteImport } from './routes/app/workout-history'
import { Route as AppLogWorkoutRouteImport } from './routes/app/log-workout'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppAdminWorkoutTemplatesRouteImport } from './routes/app/admin/workout-templates'
import { Route as AppAdminSettingsRouteImport } from './routes/app/admin/settings'
import { Route as AppAdminExercisesRouteImport } from './routes/app/admin/exercises'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutHistoryRoute = AppWorkoutHistoryRouteImport.update({
  id: '/workout-history',
  path: '/workout-history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogWorkoutRoute = AppLogWorkoutRouteImport.update({
  id: '/log-workout',
  path: '/log-workout',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminWorkoutTemplatesRoute =
  AppAdminWorkoutTemplatesRouteImport.update({
    id: '/workout-templates',
    path: '/workout-templates',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminExercisesRoute = AppAdminExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/log-workout': typeof AppLogWorkoutRoute
  '/app/workout-history': typeof AppWorkoutHistoryRoute
  '/app/admin/exercises': typeof AppAdminExercisesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/workout-templates': typeof AppAdminWorkoutTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/log-workout': typeof AppLogWorkoutRoute
  '/app/workout-history': typeof AppWorkoutHistoryRoute
  '/app/admin/exercises': typeof AppAdminExercisesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/workout-templates': typeof AppAdminWorkoutTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/log-workout': typeof AppLogWorkoutRoute
  '/app/workout-history': typeof AppWorkoutHistoryRoute
  '/app/admin/exercises': typeof AppAdminExercisesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/workout-templates': typeof AppAdminWorkoutTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/log-workout'
    | '/app/workout-history'
    | '/app/admin/exercises'
    | '/app/admin/settings'
    | '/app/admin/workout-templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/log-workout'
    | '/app/workout-history'
    | '/app/admin/exercises'
    | '/app/admin/settings'
    | '/app/admin/workout-templates'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/log-workout'
    | '/app/workout-history'
    | '/app/admin/exercises'
    | '/app/admin/settings'
    | '/app/admin/workout-templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workout-history': {
      id: '/app/workout-history'
      path: '/workout-history'
      fullPath: '/app/workout-history'
      preLoaderRoute: typeof AppWorkoutHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/log-workout': {
      id: '/app/log-workout'
      path: '/log-workout'
      fullPath: '/app/log-workout'
      preLoaderRoute: typeof AppLogWorkoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/workout-templates': {
      id: '/app/admin/workout-templates'
      path: '/workout-templates'
      fullPath: '/app/admin/workout-templates'
      preLoaderRoute: typeof AppAdminWorkoutTemplatesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/exercises': {
      id: '/app/admin/exercises'
      path: '/exercises'
      fullPath: '/app/admin/exercises'
      preLoaderRoute: typeof AppAdminExercisesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminExercisesRoute: typeof AppAdminExercisesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminWorkoutTemplatesRoute: typeof AppAdminWorkoutTemplatesRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminExercisesRoute: AppAdminExercisesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminWorkoutTemplatesRoute: AppAdminWorkoutTemplatesRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppLogWorkoutRoute: typeof AppLogWorkoutRoute
  AppWorkoutHistoryRoute: typeof AppWorkoutHistoryRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppLogWorkoutRoute: AppLogWorkoutRoute,
  AppWorkoutHistoryRoute: AppWorkoutHistoryRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
